=== biomart/martj/data/XML/DatasetView.dtd
<!ENTITY % desc_data 
                  "internalName CDATA #REQUIRED  
                   displayName CDATA #IMPLIED    
                   description CDATA #IMPLIED"
>

                   
<!ELEMENT DatasetView (Option*, DefaultFilter*, MainTable+, Key+, FilterPage+, AttributePage+)>
<!ATTLIST DatasetView %desc_data;
                      dataset CDATA #REQUIRED>

<!ELEMENT MainTable (#PCDATA)>

<!ELEMENT Key (#PCDATA)>

<!ELEMENT FilterPage (FilterGroup|DSFilterGroup|DSFilterGroup|FilterGroup)+>
<!ATTLIST FilterPage %desc_data;>

<!ELEMENT FilterGroup (FilterCollection+)>
<!ATTLIST FilterGroup %desc_data;>

<!ELEMENT DSFilterGroup EMPTY>
<!ATTLIST DSFilterGroup %desc_data;
                        handler  CDATA #IMPLIED>

<!ELEMENT FilterCollection (FilterDescription+)>
<!ATTLIST FilterCollection
                   %desc_data;>
                    
<!ELEMENT FilterDescription (Option|Enable|Disable|Enable|Option|Disable)*>
<!ATTLIST FilterDescription
                   %desc_data;
                   type          (boolean | boolean_list | boolean_num | drop_down_basic_filter | list | text | text_entry_basic_filter | tree) "list"
                   field          CDATA #IMPLIED
                   qualifier      CDATA #IMPLIED
                   legal_qualifiers          CDATA #IMPLIED
                   tableConstraint    CDATA #IMPLIED
                   key                CDATA #IMPLIED
                   handler            CDATA #IMPLIED>

<!ELEMENT Enable EMPTY>
<!ATTLIST Enable ref CDATA #REQUIRED
                 valueCondition CDATA #IMPLIED>

<!ELEMENT Disable EMPTY>
<!ATTLIST Disable ref CDATA #REQUIRED
                  valueCondition CDATA #IMPLIED>
                   
<!ELEMENT AttributePage (AttributeGroup|DSAttributeGroup|DSAttributeGroup|AttributeGroup)+>
<!ATTLIST AttributePage %desc_data;>

<!ELEMENT AttributeGroup (AttributeCollection+)>
<!ATTLIST AttributeGroup %desc_data;>

<!ELEMENT DSAttributeGroup EMPTY>
<!ATTLIST DSAttributeGroup %desc_data;
                           handler CDATA #IMPLIED>

<!ELEMENT AttributeCollection (AttributeDescription+)>
<!ATTLIST AttributeCollection
                  %desc_data;
                   maxSelect    CDATA #IMPLIED>

<!ELEMENT AttributeDescription EMPTY>
<!ATTLIST AttributeDescription
                    %desc_data;
                    field          CDATA #REQUIRED
                    tableConstraint  CDATA #REQUIRED
                    key              CDATA #REQUIRED
                    maxLength         NMTOKEN #IMPLIED
                    source                CDATA #IMPLIED
                    homepageURL  CDATA #IMPLIED
                    linkoutURL          CDATA #IMPLIED>

<!ELEMENT Option (Option|PushAction|PushAction|Option)*>
<!ATTLIST Option 
                 %desc_data;
                 isSelectable  CDATA #REQUIRED
                 value         CDATA #IMPLIED
		         ref           CDATA #IMPLIED
                 type          (boolean | boolean_list | boolean_num | drop_down_basic_filter | list | text | text_entry_basic_filter | tree) "list"
                 field     CDATA #IMPLIED
                 qualifier CDATA #IMPLIED
                 legal_qualifiers     CDATA #IMPLIED
                 tableConstraint    CDATA #IMPLIED
                 key                CDATA #IMPLIED
                 handler        CDATA #IMPLIED>

<!ELEMENT PushAction (Option)+>
<!ATTLIST PushAction
				%desc_data;
				ref CDATA #REQUIRED>

<!ELEMENT DefaultFilter (FilterDescription)>
<!ATTLIST DefaultFilter value CDATA #REQUIRED>

=== biomart/martj/data/XML/testDatasetViewRegReg.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DatasetView SYSTEM "classpath:data/XML/DatasetView.dtd">
<DatasetView dataset="test" description="For Testing Purposes Only" displayName="Test of a Registry Registry DatasetView" internalName="test_dataset_registry">
  <Option description="For Testing Purposes Only" displayName="A Test DatasetView Option" internalName="dataset option" isSelectable="true"/>
  <DefaultFilter value="1">
    <FilterDescription description="For Testing Purposes Only" displayName="A TEST ID, DOESNT EXIST" field="test_id" internalName="testDefaultFilterDescription" legal_qualifiers="in,=" qualifier="in" tableConstraint="gene_main" type="list"/>
  </DefaultFilter>
  <StarBase> test_starbase</StarBase>
  <PrimaryKey>test_primaryKey</PrimaryKey>
  <FilterPage description="For Testing Purposes Only" displayName="Test A Filter Page" internalName="testFilterPage">
    <DSFilterGroup description="For Testing Purposes Only" displayName="Test A DSFilterGroup:" handler="testHandler" internalName="testDSFilterGroup"/>
    <FilterGroup description="For Testing Purposes Only" displayName="Test A FilterGroup:" internalName="testFilterGroup">
      <FilterCollection description="For Testing Purposes Only" displayName="Test of a FilterCollection" internalName="testFilterCollection">
        <FilterDescription description="For Testing Purposes Only" displayName="A TEST ID, DOESNT EXIST" field="test_id" internalName="testFilterDescription" legal_qualifiers="in,=" qualifier="in" tableConstraint="gene_main" type="list"/>
        <FilterDescription description="For Testing Purposes Only" displayName="Filter With Enable" field="enable_test_id" internalName="enableFilter" legal_qualifiers="in,=" qualifier="in" tableConstraint="gene_main" type="list">
          <Enable ref="testFilterDescription" valueCondition="1"/>
        </FilterDescription>
        <FilterDescription description="For Testing Purposes Only" displayName="Filter With Disable" field="disable_test_id" internalName="disableFilter" legal_qualifiers="in,=" qualifier="in" tableConstraint="gene_main" type="list">
          <Disable ref="testFilterDescription" valueCondition="1"/>
        </FilterDescription>
        <FilterDescription description="For Testing Purposes Only" displayName="A TEST ID, DOESNT EXIST" field="handlerField" handler="testHandler" internalName="testHandlerFilterDescription" legal_qualifiers="in,=" qualifier="in" type="list"/>
      </FilterCollection>
      <FilterCollection description="For Testing Purposes Only" displayName="A TEST OF Options" internalName="testOptionsCollection">
        <FilterDescription description="For Testing Purposes Only" displayName="A TEST Value Option" field="value_option_id" internalName="filterDescriptionValueOption" legal_qualifiers="in,=" qualifier="in" tableConstraint="gene_main" type="list">
          <Option internalName="valueOption" isSelectable="true" value="1"/>
        </FilterDescription>
        <FilterDescription description="For Testing Purposes Only" displayName="A TEST Tree Value Option" field="test_id" internalName="filterDescriptionTreeValueOption" legal_qualifiers="in,=" qualifier="in" tableConstraint="tree_value_dm" type="list">
          <Option internalName="treeValueOption" isSelectable="false" value="">
            <Option internalName="valueOption" isSelectable="true" value="1"/>
          </Option>
        </FilterDescription>
        <FilterDescription description="For Testing Purposes Only" displayName="A TEST Option Filters" internalName="FilterDescriptionOptionFilters" type="list">
          <Option description="For Testing Purposes Only" displayName="A Test Option Filter" field="test_id" internalName="filterOptionOne" isSelectable="true" legal_qualifiers="in,=" qualifier="in" tableConstraint="filterOne_dm" type="list"/>
          <Option description="For Testing Purposes Only" displayName="A Test Option Filter" field="test_id" internalName="filterOptionTwo" isSelectable="true" legal_qualifiers="in,=" qualifier="in" tableConstraint="filterTwo_dm" type="list"/>
        </FilterDescription>
        <FilterDescription description="For Testing Purposes Only" displayName="A TEST OF OPTION WITH PUSHACTION" internalName="FilterDescriptionOptionPushAction" type="list">
          <Option description="For Testing Purposes Only" displayName="A TEST OPTION WITH PUSHACTION" field="pushActionOption_id" internalName="pushActionOption" isSelectable="true" legal_qualifiers="in,=" qualifier="in" tableConstraint="gene_main" type="list">
            <PushAction description="For Testing Purposes Only" displayName="A TEST PUSHACTION" internalName="TestValuePushAction" ref="testFilterDescription">
              <Option description="For Testing Purposes Only" displayName="A TEST PUSHACTION OPTION" internalName="testPushActionOption" isSelectable="true" value="1"/>
            </PushAction>
          </Option>
        </FilterDescription>
        <FilterDescription description="For Testing Purposes Only" displayName="A TEST OF A PUSHACTION FILTER OPTION" internalName="testPushActionOptionFilter" type="list">
          <Option description="For Testing Purposes Only" displayName="A TEST OPTION WITH PUSHACTION FILTER OPTION" internalName="PushActionFilterOption" isSelectable="true">
            <PushAction description="For Testing Purposes Only" displayName="A TEST PUSHACTION WITH OPTION FILTER" internalName="OptionFilterPushAction" ref="testFilterDescription">
              <Option description="For Testing Purposes Only" displayName="A TEST FILTER OPTION IN A PUSHACTION" field="pushActionFilterOption_id" internalName="PushActionFilterOption" isSelectable="true" legal_qualifiers="in,=" qualifier="in" tableConstraint="gene_main" type="list"/>
            </PushAction>
          </Option>
        </FilterDescription>
      </FilterCollection>
    </FilterGroup>
  </FilterPage>
  <AttributePage description="For Testing Purposes Only" displayName="Test of an Attribute Page" internalName="testAttributePage">
    <DSAttributeGroup description="For Testing Purposes Only" displayName="test of an DSAttribute Group:" handler="testHandler" internalName="testDSAttributeGroup"/>
    <AttributeGroup description="For Testing Purposes Only" displayName="test of an Attribute Group:" internalName="testAttributeGroup">
      <AttributeCollection description="For Testing Purposes Only" displayName="Test of an AttributeCollection:" internalName="testAttributeCollection" maxSelect="1">
        <AttributeDescription description="For Testing Purposes Only" displayName="Test of a AttributeDescription" field="test_id" homepageURL="http://test.org" internalName="testAttributeDescription" linkoutURL="http://test.org?test" maxLength="1" source="test source" tableConstraint="gene_main"/>
      </AttributeCollection>
    </AttributeGroup>
  </AttributePage>
</DatasetView>

=== biomart/martj/data/XML/multi_species__ae1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DatasetView SYSTEM "classpath:data/XML/DatasetView.dtd">
  <DatasetView description="ArrayExpress Experiment Mart Dataset" displayName="Array Express__Experiment" internalName="ae1" dataset="multi_species_ae1">
    
    <StarBase>multi_ae1_experiment</StarBase>
    <StarBase>multi_ae1_assay</StarBase>
    <StarBase>multi_ae1_sample</StarBase>
    
    <!--these need to be in this order for the atts to work -->
    <PrimaryKey>experiment_id</PrimaryKey>	
    <PrimaryKey>assay_id</PrimaryKey>
    <PrimaryKey>sample_id</PrimaryKey>
    <PrimaryKey>array_id</PrimaryKey>

    <FilterPage description="" displayName="Filter" internalName="default_page">
      <FilterGroup description="Filter for AE Experimental Data" displayName="Experimental Data:" internalName="experimental">
        <FilterCollection internalName="id_limit">
          <FilterDescription internalName="id_limit_filters" type="list">
            <Option description="Filter to include/exclude samples based on whether they do or don't have particualr data" displayName="Cell Line" field="has_CellLine" internalName="sample_has_CellLine" isSelectable="true" legal_qualifiers="only,excluded" tableConstraint="main" type="boolean"/>
            <Option description="Filter to include/exclude samples based on whether they do or don't have particualr data" displayName="Cell Density" field="has_CellDensity" internalName="sample_has_CellDensity" isSelectable="true" legal_qualifiers="only,excluded" tableConstraint="main" type="boolean"/>
            <Option description="Filter to include/exclude samples based on whether they do or don't have particualr data" displayName="Cell Type" field="has_CellType" internalName="sample_has_CellType" isSelectable="true" legal_qualifiers="only,excluded" tableConstraint="main" type="boolean"/>
          </FilterDescription>
          <FilterDescription description="Experiment IDs" displayName="Experiment ID" field="experiment_id"  internalName="experiment_id" legal_qualifiers="in" qualifier="in" tableConstraint="experiment_main" type="text">
          </FilterDescription>
          <FilterDescription description="Number Features" displayName="Number Features" field="value"  internalName="array_number_features" legal_qualifiers=">" qualifier=">" type="text">
          </FilterDescription>
          <FilterDescription description="Assay type" displayName="Assay Type" field="assay_type"  internalName="assay_type" legal_qualifiers="=" qualifier="=" tableConstraint="_sample_main" type="text">
          </FilterDescription>
          <FilterDescription description="Sample species" displayName="Sample Species" field="sample_species"  internalName="sample_species" legal_qualifiers="=" qualifier="=" tableConstraint="main" type="text">
          </FilterDescription>
          <FilterDescription description="Organism Part" displayName="Organism Part" field="value"  internalName="sample_organism_part" legal_qualifiers="=" qualifier="=" tableConstraint="_sample_OrganismPart" type="text">
          </FilterDescription>
          <FilterDescription description="Experiment accessions" displayName="Experiment Accession" field="experiment_accession"  internalName="experiment_accession" legal_qualifiers="=" qualifier="=" type="text">
          </FilterDescription>
          <FilterDescription description="Experiment Performer" displayName="Experiment Performer" field="experiment_performer"  internalName="experiment_performer" legal_qualifiers="=" qualifier="=" type="text">
          </FilterDescription>
          <FilterDescription description="Array name" displayName="Array name" field="array_name"  internalName="array_name" legal_qualifiers="=" qualifier="=" type="text">
          </FilterDescription>
          <FilterDescription description="Array ID" displayName="Array ID" field="array_id"  internalName="array_id" legal_qualifiers="in" qualifier="in" type="text">
          </FilterDescription>
          
        </FilterCollection>
      </FilterGroup>
    </FilterPage>

    <AttributePage description="General Sample Features" displayName="Features" internalName="feature_page">

      <AttributeGroup description="Attributes relating to the experiments, arrays, assays and samples." displayName="Sample" internalName="sample">

         <AttributeCollection description="Attributes related to experiment." displayName="Experiment and Array Attributes:" internalName="experiment_attributes">
           <AttributeDescription description="Experimental Factor" displayName="Experimental Factor" field="value" internalName="experiment_experimental_factor" tableConstraint="_experimentalFactor_dm" maxLength="12"/>
           <AttributeDescription description="Experiment ID" displayName="Experiment ID" field="experiment_id" internalName="experiment_id" tableConstraint="main" maxLength="12"/>
           <AttributeDescription description="Experiment Type" displayName="Experiment Type" field="experiment_type" internalName="experiment_type" tableConstraint="main" maxLength="12"/>
           <AttributeDescription description="Experiment Accession" displayName="Experiment Accession" field="experiment_accession" internalName="experiment_accession" tableConstraint="main" maxLength="12"/>
           <AttributeDescription description="Array Accession" displayName="Array Accession" field="array_accession" internalName="array_accession" tableConstraint="main" maxLength="12"/>
           <AttributeDescription description="Array ID" displayName="Array ID" field="array_id" internalName="array_id" tableConstraint="main" maxLength="12"/>
           <AttributeDescription description="Array Type" displayName="Array Type" field="array_type" internalName="array_type" tableConstraint="main" maxLength="12"/>
           <AttributeDescription description="Experiment Performer" displayName="Experiment Performer" field="experiment_performer" internalName="experiment_performer" tableConstraint="main" maxLength="12"/>
           <AttributeDescription description="Experiment Lab" displayName="Experiment Lab" field="experiment_lab" internalName="experiment_lab" tableConstraint="main" maxLength="12"/>
           <AttributeDescription description="Array Name" displayName="Array Name" field="array_name" internalName="array_name" tableConstraint="main" maxLength="12"/>
           <AttributeDescription description="Array Provider" displayName="Array Provider" field="array_provider" internalName="array_provider" tableConstraint="main" maxLength="12"/>
           <AttributeDescription description="Number of Features" displayName="Number of Features" field="value" internalName="array_number_features" tableConstraint="_numberOfFeatures_dm" maxLength="12"/>
         </AttributeCollection>
         <AttributeCollection description="Attributes related to assay." displayName="Assay Attributes:" internalName="assay_attributes">
           <AttributeDescription description="Assay ID" displayName="Assay ID" field="assay_id" internalName="assay_id" tableConstraint="main" maxLength="12"/>
           <AttributeDescription description="Assay Type" displayName="Assay Type" field="assay_type" internalName="assay_type" tableConstraint="main" maxLength="12"/>
           <AttributeDescription description="Assay Compound" displayName="Assay Compound" field="value" internalName="assay_compound" tableConstraint="_compound_dm" maxLength="12"/>
         </AttributeCollection>
         <AttributeCollection description="Attributes related to sample." displayName="sample Attributes:" internalName="sample_attributes" maxSelect="3">
          
          <AttributeDescription description="Sample ID" displayName="Sample ID" field="sample_id" internalName="sample_id" tableConstraint="main" maxLength="12"/>
         <AttributeDescription description="Sample Type" displayName="Sample Type" field="sample_type" internalName="sample_type" tableConstraint="main" maxLength="12"/>
         
        <AttributeDescription description="Sample Species" displayName="Sample Species" field="sample_species" internalName="sample_species" tableConstraint="main" maxLength="12"/>
        
          <AttributeDescription description="Cell Line" displayName="Cell Line" field="value" internalName="sample_cell_line" tableConstraint="_CellLine_dm" maxLength="12"/>
          <AttributeDescription description="Organism Part" displayName="Organism Part" field="value" internalName="sample_organism_part" tableConstraint="_OrganismPart_dm" maxLength="12"/>
          <AttributeDescription description="Treatment Compound" displayName="Treatment Compound" field="value" internalName="sample_treatment_compound" tableConstraint="_treatmentCompound_dm" maxLength="12"/>
          <AttributeDescription description="Sample Sex" displayName="Sample Sex" field="value" internalName="sample_sex" tableConstraint="_Sex_dm" maxLength="12"/>
          <AttributeDescription description="Developmental Stage" displayName="Developmental Stage" field="value" internalName="sample_developmental_stage" tableConstraint="_DevelopmentalStage_dm" maxLength="12"/>
          <AttributeDescription description="Cell Type" displayName="Cell Type" field="value" internalName="sample_cell_type" tableConstraint="_CellType_dm" maxLength="12"/>
          <AttributeDescription description="Cell Density" displayName="Cell Density" field="value" internalName="sample_cell_density" tableConstraint="_CellDensity_dm" maxLength="12"/>
          
        </AttributeCollection>
      </AttributeGroup>
    </AttributePage>
  </DatasetView>
