=== biomart/martj/data/XML/MartConfiguration.dtd
<!ENTITY % desc_data 
                  "internalName CDATA #REQUIRED  
                   displayName CDATA #IMPLIED    
                   description CDATA #IMPLIED"
>

<!-- Ensembl Source, Homepage, and LinkoutURL for AttributeDescriptions -->

<!-- Top-level Objects --> 
<!ELEMENT MartConfiguration (Dataset+)>
<!ATTLIST MartConfiguration %desc_data;>
                   
<!ELEMENT Dataset (StarBase+, PrimaryKey+, FilterPage+, AttributePage+)>
<!ATTLIST Dataset %desc_data;>

<!ELEMENT StarBase (#PCDATA)>

<!ELEMENT PrimaryKey (#PCDATA)>

<!ELEMENT FilterPage (FilterGroup|DSFilterGroup|DSFilterGroup|FilterGroup)+>
<!ATTLIST FilterPage %desc_data;>

<!ELEMENT FilterGroup (FilterSet*, FilterCollection+)>
<!ATTLIST FilterGroup %desc_data;>

<!ELEMENT DSFilterGroup EMPTY>
<!ATTLIST DSFilterGroup %desc_data;
                        objectCode  CDATA #IMPLIED>

<!ELEMENT FilterSet (FilterSetDescription+)>
<!ATTLIST FilterSet 
                       %desc_data;                       
                       type   CDATA #REQUIRED>

<!ELEMENT FilterSetDescription EMPTY>
<!ATTLIST FilterSetDescription %desc_data;
                       tableConstraintModifier CDATA #IMPLIED
                       fieldNameModifier CDATA #IMPLIED> 

<!ELEMENT FilterCollection (Option|UIFilterDescription|UIDSFilterDescription|UIDSFilterDescription|UIFilterDescription)+>
<!ATTLIST FilterCollection
                   %desc_data;
                   filterSetName       CDATA #IMPLIED
                   type                CDATA #REQUIRED>
                    
<!ELEMENT UIFilterDescription EMPTY>
<!ATTLIST UIFilterDescription
                   %desc_data;
                   type               CDATA #REQUIRED
                   fieldName          CDATA #REQUIRED
                   qualifier          CDATA #IMPLIED
                   filterSetReq       CDATA #IMPLIED
                   tableConstraint    CDATA #IMPLIED
                   optionName         CDATA #IMPLIED>

<!ELEMENT UIDSFilterDescription EMPTY>
<!ATTLIST UIDSFilterDescription
                   %desc_data;
                   type               CDATA #REQUIRED
                   filterSetReq       CDATA #IMPLIED
                   optionName         CDATA #IMPLIED
                   objectCode         CDATA #REQUIRED>
                   
<!ELEMENT AttributePage (AttributeGroup|DSAttributeGroup|DSAttributeGroup|AttributeGroup)+>
<!ATTLIST AttributePage %desc_data;>

<!ELEMENT AttributeGroup (AttributeCollection+)>
<!ATTLIST AttributeGroup %desc_data;>

<!ELEMENT DSAttributeGroup EMPTY>
<!ATTLIST DSAttributeGroup %desc_data;
                           objectCode CDATA #IMPLIED>

<!ELEMENT AttributeCollection (UIAttributeDescription+)>
<!ATTLIST AttributeCollection
                  %desc_data;
                   maxSelect    CDATA #IMPLIED>

<!ELEMENT UIAttributeDescription EMPTY>
<!ATTLIST UIAttributeDescription
                    %desc_data;
                    fieldName          CDATA #REQUIRED
                    tableConstraint  CDATA #IMPLIED
                    maxLength         NMTOKEN #IMPLIED
                    source                CDATA #IMPLIED
                    homepageURL  CDATA #IMPLIED
                    linkoutURL          CDATA #IMPLIED>

<!ELEMENT Option (Option*)>
<!ATTLIST Option 
                 %desc_data;
                 isSelectable  CDATA #REQUIRED>

=== biomart/martj/src/java/org/ensembl/mart/explorer/XML/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE MartConfiguration SYSTEM "MartConfiguration.dtd">
<MartConfiguration description="First Mart Created from version 14 Ensembl Datasources" displayName="Ensembl Mart version 14.1" internalName="ensembl_mart_14_1">
  <Dataset description="For Testing Purposes Only" displayName="Test of a Dataset" internalName="test_dataset">
    <StarBase>test_starbase</StarBase>
    <PrimaryKey>test_primaryKey</PrimaryKey>
    <FilterPage description="For Testing Purposes Only" displayName="Test A Filter Page" internalName="testFilterPage">
      <FilterGroup description="For Testing Purposes Only" displayName="Test A FilterGroup:" internalName="testFilterGroup">
        <FilterSet description="For Testing Purposes Only" displayName="Test of a Filter Set" internalName="testFilterSet" type="radio">
          <FilterSetDescription description="For Testing Purposes Only" displayName="Test of a FilterSetDescription" fieldNameModifier="ensembl" internalName="testFilterSetDescription" tableConstraintModifier="ensemblgene"/>
        </FilterSet>
        <FilterCollection description="For Testing Purposes Only" displayName="Test of a FilterCollection" internalName="testFilterCollection" type="list">
          <UIFilterDescription description="For Testing Purposes Only" displayName="A TEST ID, DOESNT EXIST" fieldName="test_id" internalName="testUIFilterDescription" qualifier="in" tableConstraint="gene_main" type="list"/>
          <UIDSFilterDescription description="For Testing Purposes Only" displayName="A TEST ID, DOESNT EXIST" internalName="testUIDSFilterDescription" objectCode="testObjectCode" type="list"/>
        </FilterCollection>
        <FilterCollection description="For Testing Purposes Only" displayName="A TEST OF FILTER SETS" filterSetName="testFilterSet" internalName="testFilterSetCollection" type="list">
          <UIFilterDescription description="For Testing Purposes Only" displayName="A TEST FIELD MODIFIER" fieldName="syn_exclusive" filterSetReq="field" internalName="filterSetUIFilterDescriptionField" qualifier="in" tableConstraint="gene_main" type="list"/>
          <UIFilterDescription description="For Testing Purposes Only" displayName="A TEST TABLE MODIFIER" fieldName="gene_stable_id_v" filterSetReq="table" internalName="filterSetUIFilterDescriptionTable" qualifier="in" tableConstraint="_dm" type="list"/>
          <UIDSFilterDescription description="For Testing Purposes Only" displayName="A TEST ID, DOESNT EXIST" filterSetReq="table" internalName="filterSetUIDSFilterDescription" objectCode="testObjectCode" type="list"/>
        </FilterCollection>
      </FilterGroup>
    </FilterPage>
    <AttributePage description="For Testing Purposes Only" displayName="Test of an Attribute Page" internalName="testAttributePage">
      <AttributeGroup description="For Testing Purposes Only" displayName="test of an Attribute Group:" internalName="testAttributeGroup">
        <AttributeCollection description="For Testing Purposes Only" displayName="Test of an AttributeCollection:" internalName="testAttributeCollection" maxSelect="1">
          <UIAttributeDescription description="For Testing Purposes Only" displayName="Test of a UIAttributeDescription" fieldName="test_id" homepageURL="http://test.org" internalName="testUIAttributeDescription" linkoutURL="http://test.org?test" maxLength="1" source="test source" tableConstraint="gene_main"/>
          <UIDSAttributeDescription description="For Testing Purposes Only" displayName="Test of a UIDSAttributeDescription" homepageURL="http://test.org" internalName="testUIDSAttributeDescription" linkoutURL="http://test.org?test" objectCode="testObjectCode" source="test source"/>
        </AttributeCollection>
      </AttributeGroup>
    </AttributePage>
  </Dataset>
</MartConfiguration>
